### ISSUE TITLE
kritischer Fehler auf Seiten mit Shortcode

### ISSUE THREAD

**Issue by platzhersh** [velafrica/velafrica-wpack-collectionevents#2]
betrifft: v0.0.5

<img width="1113" alt="image" src="https://user-images.githubusercontent.com/1445827/124390720-27eaef00-dced-11eb-8615-21604baa15be.png">

local-wordpress | [Sun Jul 04 15:23:46.652754 2021] [php7:error] [pid 23] [client 172.18.0.1:61102] PHP Fatal error: Uncaught LogicException: Manifest /var/www/html/wp-content/plugins/velafrica-collectionevents/dist/reactapp/manifest.json does not exist. in /var/www/html/wp-content/plugins/velafrica-collectionevents/vendor/wpackio/enqueue/inc/Enqueue.php:427\nStack trace:\n#0 /var/www/html/wp-content/plugins/velafrica-collectionevents/vendor/wpackio/enqueue/inc/Enqueue.php(294): WPackio\\Enqueue->getManifest('reactapp')\n#1 /var/www/html/wp-content/plugins/velafrica-collectionevents/vendor/wpackio/enqueue/inc/Enqueue.php(170): WPackio\\Enqueue->getAssets('reactapp', 'main', Array)\n#2 /var/www/html/wp-content/plugins/velafrica-collectionevents/vendor/wpackio/enqueue/inc/Enqueue.php(229): WPackio\\Enqueue->register('reactapp', 'main', Array)\n#3 /var/www/html/wp-content/plugins/velafrica-collectionevents/inc/class-velafrica-collectionevents-plugin-init.php(28): WPackio\\Enqueue->enqueue('reactapp', 'main', Array)\n#4 /var/www/html/wp-includes/shortcodes.php(343): Velafrica_Collectionevents_Plugin_Init->reactapp('', '', 'velafrica-coll in /var/www/html/wp-content/plugins/velafrica-collectionevents/vendor/wpackio/enqueue/inc/Enqueue.php on line 427, referer: http://localhost/wp-admin/edit.php?post_type=page

local-wordpress | 172.18.0.1 - - [04/Jul/2021:15:23:43 +0000] "GET /wp-admin/post.php?post=23&action=edit HTTP/1.1" 500 3255 "http://localhost/wp-admin/edit.php?post_type=page" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0"

**Comment by platzhersh** [comment]
yarn build 

zwingend nötig bevor

    yarn archive
